version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    volumes:
      - ./server:/usr/src/app
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/usr/src/app
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: steam_admin
      POSTGRES_PASSWORD: steam_pass
      POSTGRES_DB: steam_ticket
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
